# Generated by Django 2.2.1 on 2019-05-29 09:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLASS_NAME', models.CharField(blank=True, choices=[('1 ICSE ', '1 ICSE '), ('1 CBSE', '1 CBSE'), ('2 ICSE', '2 ICSE'), ('2 CBSE', '2 CBSE'), ('3 ICSE', '3 ICSE'), ('3A CBSE', '3A CBSE'), ('3B CBSE', '3B CBSE'), ('4A ICSE', '4A ICSE'), ('4B ICSE', '4B ICSE'), ('4 CBSE', '4 CBSE'), ('5A ICSE', '5A ICSE'), ('5B ICSE', '5B ICSE'), ('5 CBSE', '5 CBSE'), ('6A ICSE', '6A ICSE'), ('6B ICSE', '6B ICSE'), ('6 CBSE', '6 CBSE'), ('7A ICSE', '7A ICSE'), ('7B ICSE', '7B ICSE'), ('7 CBSE', '7 CBSE'), ('8 ICSE', '8 ICSE'), ('8 CBSE', '8 CBSE'), ('9 ICSE', '9 ICSE'), ('9 CBSE', '9 CBSE'), ('10 ICSE', '10 ICSE'), ('10 CBSE', '10 CBSE')], default='', max_length=150)),
                ('SUBJECT', models.CharField(blank=True, choices=[('English Language', 'English Language'), ('English Literature', 'English Literature'), ('Kannada', 'Kannada'), ('Hindi', 'Hindi'), ('Mathematics', 'Mathematics'), ('Evs', 'Evs'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History Civics', 'History Civics'), ('Geography', 'Geography'), ('Computer Application', 'Computer Application')], default='', max_length=150)),
                ('NAME_OF_THE_LESSON', models.CharField(default='', max_length=500)),
                ('AREA_OF_INTEREST', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Age', 'Age'), ('Gender', 'Gender'), ('Widely Discussed', 'Widely Discussed'), ('Contemporary', 'Contemporary'), ('Within the Competency of Children', 'Within the Competency of Children'), ('Social Religious Linguistic National Identity', 'Social Religious Linguistic National Identity'), ('Does Not Induce Interest', 'Does Not Induce Interest')], default='', max_length=145)),
                ('INSTRUCTIONAL_OBJECTIVE_1', models.CharField(blank=True, default='', max_length=500)),
                ('INSTRUCTIONAL_OBJECTIVE_2', models.CharField(blank=True, default='', max_length=500)),
                ('INSTRUCTIONAL_OBJECTIVE_3', models.CharField(blank=True, default='', max_length=500)),
                ('INSTRUCTIONAL_OBJECTIVE_4', models.CharField(blank=True, default='', max_length=500)),
                ('INSTRUCTIONAL_OBJECTIVE_5', models.CharField(blank=True, default='', max_length=500)),
                ('STUDENTS_EXPERIENCE_VISUAL', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('AUDITORY', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('FINE_MOTOR', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('GROSS_MOTOR', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('TEACHING_POINT_1', models.CharField(blank=True, default='', max_length=500)),
                ('DOMAIN', models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150)),
                ('TYPE_OF_LEARNING_ACTIVITY_1', models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150)),
                ('LEARNING_ACTIVITY', models.CharField(blank=True, default='', max_length=500)),
                ('INTELLIGENCE_USED', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110)),
                ('IMAGE_IF_ANY', models.ImageField(blank=True, default='', upload_to='images/')),
                ('VIDEO_LINK_IF_ANY', models.CharField(blank=True, default='', max_length=1500)),
                ('LEARNING_MATERIAL_USED', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360)),
                ('ASSESSMENT_OF_LEARNING_ACTIVITY', models.CharField(blank=True, default='', max_length=500)),
                ('TEACHING_POINT_2', models.CharField(blank=True, default='', max_length=500)),
                ('DOMAIN_2', models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150)),
                ('TYPE_OF_LEARNING_ACTIVITY_2', models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150)),
                ('LEARNING_ACTIVITY_2', models.CharField(blank=True, default='', max_length=500)),
                ('INTELLIGENCE_USED_2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110)),
                ('IMAGE_IF_ANY_2', models.ImageField(blank=True, default='', upload_to='images/')),
                ('VIDEO_LINK_IF_ANY_2', models.CharField(blank=True, default='', max_length=1500)),
                ('LEARNING_MATERIAL_USED_2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360)),
                ('ASSESSMENT_OF_LEARNING_ACTIVITY_2', models.CharField(blank=True, default='', max_length=500)),
                ('HOMEWORK', models.TextField(blank=True)),
                ('COMMENTS', models.TextField(blank=True)),
                ('STATUS', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Review', 'Review'), ('Pending', 'Pending')], default='Pending', max_length=150)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publish_date', '-updated', '-timestamp'],
            },
        ),
    ]
