# Generated by Django 2.2.1 on 2019-05-11 19:39

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLASS_NAME', models.CharField(blank=True, choices=[('1 Icse ', '1 Icse '), ('1 Cbse', '1 Cbse'), ('2 Icse', '2 Icse'), ('2 Cbse', '2 Cbse'), ('3 Icse', '3 Icse'), ('3A Cbse', '3A Cbse'), ('3B Cbse', '3B Cbse'), ('4A Icse', '4A Icse'), ('4B Icse', '4B Icse'), ('4 Cbse', '4 Cbse'), ('5A Icse', '5A Icse'), ('5B Icse', '5B Icse'), ('5 Cbse', '5 Cbse'), ('6A Icse', '6A Icse'), ('6B Icse', '6B Icse'), ('6 Cbse', '6 Cbse'), ('7A Icse', '7A Icse'), ('7B Icse', '7B Icse'), ('7 Cbse', '7 Cbse'), ('8 Icse', '8 Icse'), ('8 Cbse', '8 Cbse'), ('9 Icse', '9 Icse'), ('9 Cbse', '9 Cbse'), ('10 Icse', '10 Icse'), ('10 Cbse', '10 Cbse')], default='', max_length=150)),
                ('SUBJECT', models.CharField(blank=True, choices=[('English Language', 'English Language'), ('English Literature', 'English Literature'), ('Kannada', 'Kannada'), ('Hindi', 'Hindi'), ('Mathematics', 'Mathematics'), ('Evs', 'Evs'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History Civics', 'History Civics'), ('Geography', 'Geography'), ('Computer Application', 'Computer Application')], default='', max_length=150)),
                ('NAME_OF_THE_LESSON', models.CharField(blank=True, default='', max_length=500)),
                ('INSTRUCTIONAL_OBJECTIVE_1', models.CharField(blank=True, default='', max_length=500)),
                ('INSTRUCTIONAL_OBJECTIVE_2', models.CharField(blank=True, default='', max_length=500)),
                ('INSTRUCTIONAL_OBJECTIVE_3', models.CharField(blank=True, default='', max_length=500)),
                ('INSTRUCTIONAL_OBJECTIVE_4', models.CharField(blank=True, default='', max_length=500)),
                ('INSTRUCTIONAL_OBJECTIVE_5', models.CharField(blank=True, default='', max_length=500)),
                ('TEACHING_POINT_1', models.CharField(blank=True, default='', max_length=500)),
                ('DOMAIN', models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150)),
                ('AREA_OF_INTEREST', multiselectfield.db.fields.MultiSelectField(choices=[('Age', 'Age'), ('Gender', 'Gender'), ('Widely Discussed', 'Widely Discussed'), ('Contemporary', 'Contemporary'), ('Within the Competency of Children', 'Within the Competency of Children'), ('Social Religious Linguistic National Identity', 'Social Religious Linguistic National Identity'), ('Does Not Induce Interest', 'Does Not Induce Interest')], default='AGE', max_length=145)),
                ('TYPE_OF_LEARNING_ACTIVITY_1', models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='Choose', max_length=150)),
                ('LEARNING_ACTIVITY', models.CharField(blank=True, default='', max_length=500)),
                ('STUDENTS_EXPERIENCE_VISUAL', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='1', max_length=150)),
                ('AUDITORY', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('FINE_MOTOR', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('GROSS_MOTOR', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('INTELLIGENCE_USED', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110)),
                ('IMAGE_IF_ANY', models.ImageField(blank=True, default='', upload_to='images/')),
                ('VIDEO_LINK_IF_ANY', models.CharField(blank=True, default='', max_length=1500)),
                ('LEARNING_MATERIAL_USED', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop with Projector', 'Laptop with Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts')], default='', max_length=93)),
                ('ASSESSMENT_OF_LEARNING_ACTIVITY', models.CharField(blank=True, default='', max_length=500)),
                ('TEACHING_POINT_2', models.CharField(blank=True, default='', max_length=500)),
                ('DOMAIN_2', models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150)),
                ('AREA_OF_INTEREST_2', multiselectfield.db.fields.MultiSelectField(choices=[('Age', 'Age'), ('Gender', 'Gender'), ('Widely Discussed', 'Widely Discussed'), ('Contemporary', 'Contemporary'), ('Within the Competency of Children', 'Within the Competency of Children'), ('Social Religious Linguistic National Identity', 'Social Religious Linguistic National Identity'), ('Does Not Induce Interest', 'Does Not Induce Interest')], default='', max_length=145)),
                ('TYPE_OF_LEARNING_ACTIVITY_2', models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='Choose', max_length=150)),
                ('LEARNING_ACTIVITY_2', models.CharField(default='', max_length=500)),
                ('STUDENTS_EXPERIENCE_VISUAL_2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('AUDITORY_2', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('FINE_MOTOR_2', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('GROSS_MOTOR_2', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150)),
                ('INTELLIGENCE_USED_2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110)),
                ('IMAGE_IF_ANY_2', models.ImageField(blank=True, default='', upload_to='images/')),
                ('VIDEO_LINK_IF_ANY_2', models.CharField(blank=True, default='', max_length=1500)),
                ('LEARNING_MATERIAL_USED_2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop with Projector', 'Laptop with Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts')], default='', max_length=93)),
                ('ASSESSMENT_OF_LEARNING_ACTIVITY_2', models.CharField(blank=True, default='', max_length=500)),
                ('HOMEWORK', models.TextField(blank=True)),
                ('COMMENTS', models.TextField(blank=True)),
                ('STATUS', models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Edit and Resend', 'Edit and Resend')], default='', max_length=150)),
            ],
        ),
    ]
