# Generated by Django 2.2.1 on 2019-05-04 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='FROM_DATE',
        ),
        migrations.RemoveField(
            model_name='post',
            name='TO_DATE',
        ),
    ]
