# Generated by Django 2.2.1 on 2019-05-30 02:38

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='DOMAIN_3',
            field=models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='DOMAIN_4',
            field=models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='DOMAIN_5',
            field=models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='IMAGE_IF_ANY_3',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='IMAGE_IF_ANY_4',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='IMAGE_IF_ANY_5',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='INTELLIGENCE_USED_3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110),
        ),
        migrations.AddField(
            model_name='post',
            name='INTELLIGENCE_USED_4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110),
        ),
        migrations.AddField(
            model_name='post',
            name='INTELLIGENCE_USED_5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110),
        ),
        migrations.AddField(
            model_name='post',
            name='LEARNING_ACTIVITY_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='LEARNING_ACTIVITY_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='LEARNING_ACTIVITY_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360),
        ),
        migrations.AddField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360),
        ),
        migrations.AddField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360),
        ),
        migrations.AddField(
            model_name='post',
            name='TEACHING_POINT_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='TEACHING_POINT_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='TEACHING_POINT_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_3',
            field=models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_4',
            field=models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_5',
            field=models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150),
        ),
        migrations.AddField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_3',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_4',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_5',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
    ]
