# Generated by Django 2.2.1 on 2019-05-14 18:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='AUDITORY',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='FINE_MOTOR',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='GROSS_MOTOR',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
    ]
