# Generated by Django 2.2.1 on 2019-05-26 08:28

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='AREA_OF_INTEREST',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Age', 'Age'), ('Gender', 'Gender'), ('Widely Discussed', 'Widely Discussed'), ('Contemporary', 'Contemporary'), ('Within the Competency of Children', 'Within the Competency of Children'), ('Social Religious Linguistic National Identity', 'Social Religious Linguistic National Identity'), ('Does Not Induce Interest', 'Does Not Induce Interest')], default='', max_length=145),
        ),
        migrations.AlterField(
            model_name='post',
            name='STUDENTS_EXPERIENCE_VISUAL',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
    ]
