# Generated by Django 2.2.1 on 2019-06-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190530_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='AREA_OF_INTEREST',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='AUDITORY',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='CLASS_NAME',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='COMMENTS',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='FINE_MOTOR',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='GROSS_MOTOR',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='HOMEWORK',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='STATUS',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='STUDENTS_EXPERIENCE_VISUAL',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='SUBJECT',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_1',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_2',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_3',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_4',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_5',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
