# Generated by Django 2.2.1 on 2019-05-14 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20190514_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='AUDITORY',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='FINE_MOTOR',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='GROSS_MOTOR',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
    ]
