# Generated by Django 2.2.1 on 2019-06-01 19:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20190601_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='AREA_OF_INTEREST',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Age', 'Age'), ('Gender', 'Gender'), ('Widely Discussed', 'Widely Discussed'), ('Contemporary', 'Contemporary'), ('Within the Competency of Children', 'Within the Competency of Children'), ('Social Religious Linguistic National Identity', 'Social Religious Linguistic National Identity'), ('Does Not Induce Interest', 'Does Not Induce Interest')], default='', max_length=145),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='ASSESSMENT_OF_LEARNING_ACTIVITY_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='AUDITORY',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='CLASS_NAME',
            field=models.CharField(blank=True, choices=[('1 ICSE ', '1 ICSE '), ('1 CBSE', '1 CBSE'), ('2 ICSE', '2 ICSE'), ('2 CBSE', '2 CBSE'), ('3 ICSE', '3 ICSE'), ('3A CBSE', '3A CBSE'), ('3B CBSE', '3B CBSE'), ('4A ICSE', '4A ICSE'), ('4B ICSE', '4B ICSE'), ('4 CBSE', '4 CBSE'), ('5A ICSE', '5A ICSE'), ('5B ICSE', '5B ICSE'), ('5 CBSE', '5 CBSE'), ('6A ICSE', '6A ICSE'), ('6B ICSE', '6B ICSE'), ('6 CBSE', '6 CBSE'), ('7A ICSE', '7A ICSE'), ('7B ICSE', '7B ICSE'), ('7 CBSE', '7 CBSE'), ('8 ICSE', '8 ICSE'), ('8 CBSE', '8 CBSE'), ('9 ICSE', '9 ICSE'), ('9 CBSE', '9 CBSE'), ('10 ICSE', '10 ICSE'), ('10 CBSE', '10 CBSE')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='COMMENTS',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN',
            field=models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN_2',
            field=models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN_3',
            field=models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN_4',
            field=models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='DOMAIN_5',
            field=models.CharField(blank=True, choices=[('Knowledge', 'Knowledge'), ('Understanding', 'Understanding'), ('Application', 'Application'), ('Analysis', 'Analysis'), ('Evaluation', 'Evaluation'), ('Creative', 'Creative')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='FINE_MOTOR',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='GROSS_MOTOR',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='HOMEWORK',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY_2',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY_3',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY_4',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='IMAGE_IF_ANY_5',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED_2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED_3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED_4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='post',
            name='INTELLIGENCE_USED_5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Verbal Linguistic\t', 'Verbal Linguistic'), ('Mathematical', 'Mathematical'), ('Musical', 'Musical'), ('Visual Spacial', 'Visual Spacial'), ('Bodily Kinesthetic', 'Bodily Kinesthetic'), ('Intrapersonal', 'Intrapersonal'), ('Naturalist', 'Naturalist'), ('Existential', 'Existential')], default='', max_length=110),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_ACTIVITY_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_2',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_3',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_4',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360),
        ),
        migrations.AlterField(
            model_name='post',
            name='LEARNING_MATERIAL_USED_5',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Whiteboard', 'Whiteboard'), ('Laptop With Projector', 'Laptop With Projector'), ('Model From Lab', 'Model From Lab'), ('Live Model', 'Live Model'), ('Magnets', 'Magnets'), ('Electrical Circuits', 'Electrical Circuits'), ('Charts', 'Charts'), ('Glass Slab', 'Glass Slab'), ('Prism', 'Prism'), ('Materials Around Them', 'Materials Around Them'), ('Flash Cards', 'lash Cards'), ('Dictionary', 'Dictionary'), ('Textbook/sm/hm', 'Textbook/sm/hm'), ('Beads/abacus', 'Beads/abacus'), ('Lens / Mirrors', 'ens / Mirrors'), ('Weighing Machines', 'Weighing Machines'), ('Spirit Lamp', 'Spirit Lamp'), ('Lab Glass Materials And Chemicals', 'Lab Glass Materials And Chemicals'), ('Newspapaer Clip', 'Newspapaer Clip'), ('Globe', 'Globe'), ('Maps', 'Maps'), ('Measurement Tapes', 'Measurement Tapes'), ('Clock', 'Clock'), ('Number Blocks', 'Number Blocks'), ('Seeds', 'Seeds'), ('Audio Players', 'Audio Players'), ('Others', 'Others'), ('Atlas', 'Atlas')], default='', max_length=360),
        ),
        migrations.AlterField(
            model_name='post',
            name='STATUS',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Review', 'Review'), ('Pending', 'Pending')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='STUDENTS_EXPERIENCE_VISUAL',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='SUBJECT',
            field=models.CharField(blank=True, choices=[('English Language', 'English Language'), ('English Literature', 'English Literature'), ('Kannada', 'Kannada'), ('Hindi', 'Hindi'), ('Mathematics', 'Mathematics'), ('Evs', 'Evs'), ('Science', 'Science'), ('Social Studies', 'Social Studies'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('History Civics', 'History Civics'), ('Geography', 'Geography'), ('Computer Application', 'Computer Application')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_1',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_2',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_3',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_4',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='TEACHING_POINT_5',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_1',
            field=models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_2',
            field=models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_3',
            field=models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_4',
            field=models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='TYPE_OF_LEARNING_ACTIVITY_5',
            field=models.CharField(blank=True, choices=[('Demo with Visual_aid', 'Demo with Visual_aid'), ('Demo with Teaching Aid', 'Demo with Teaching Aid'), ('Demo with Learning Aid', 'Demo with Learning Aid'), ('Demo with white Board', 'Demo with white Board'), ('Discussion', 'Discussion'), ('Oral', 'Oral'), ('Rhymes_recitation', 'Rhymes_recitation'), ('People_play', 'People_play')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_2',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_3',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_4',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='post',
            name='VIDEO_LINK_IF_ANY_5',
            field=models.CharField(blank=True, default='', max_length=1500),
        ),
    ]
