# Generated by Django 2.2.1 on 2019-05-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_author_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
