# Generated by Django 2.2.1 on 2019-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20190526_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='AUDITORY',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='', max_length=150),
        ),
    ]
