# Generated by Django 2.2.1 on 2019-06-03 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_auto_20190602_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='FROM_DATE',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='TO_DATE',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
