# Generated by Django 2.2.1 on 2019-06-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0008_auto_20190603_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='CLASS_NAME',
            field=models.CharField(blank=True, choices=[('1 ICSE', '1 ICSE'), ('1A CBSE', '1A CBSE'), ('1B CBSE', '1B CBSE'), ('2 ICSE', '2 ICSE'), ('2 CBSE', '2 CBSE'), ('3 ICSE', '3 ICSE'), ('3 CBSE', '3 CBSE'), ('4 ICSE', '4 ICSE'), ('4A CBSE', '4A CBSE'), ('4B CBSE', '4B CBSE'), ('5A ICSE', '5A ICSE'), ('5B ICSE', '5B ICSE'), ('5 CBSE', '5 CBSE'), ('6A ICSE', '6A ICSE'), ('6B ICSE', '6B ICSE'), ('6 CBSE', '6 CBSE'), ('7A ICSE', '7A ICSE'), ('7B ICSE', '7B ICSE'), ('7 CBSE', '7 CBSE'), ('8 ICSE', '8 ICSE'), ('8 CBSE', '8 CBSE'), ('9 ICSE', '9 ICSE'), ('9 CBSE', '9 CBSE'), ('10 ICSE', '10 ICSE'), ('10 CBSE', '10 CBSE')], default='', max_length=150),
        ),
    ]
